/**
 * Birth chart Lal Kitaab — planet-in-house descriptions and remedies in English.
 * Translated from birth chart Hindi (BIRTH_CHART_PLANET_IN_HOUSE_HI) only.
 * Used when Birth Chart + English is selected.
 */

export const BIRTH_CHART_PLANET_IN_HOUSE: Record<string, string> = {
  'Ke-1':
    'According to Lal Kitab birth chart, Ketu is in house 1 in your chart. House 1 is influenced by Sun and Mars, so Ketu\'s effect is seen as weak here. You tend to involve people in unnecessary talk or question-answer. Ketu\'s result here is good. You have increased possibility of son, grandson or your sister\'s son. Even if you are transferred, your journey may get postponed at the last moment. Your birth may not have been near your father\'s house. You may have blood-related disease.',
  'Ke-2':
    'According to Lal Kitab birth chart, Ketu is in house 2 in your chart. House 2 is influenced by Ketu, so you may benefit from travel-related business. You cannot sit in one place and work. You have good possibility of wife\'s happiness. You will do business worth lakhs but will not be able to save. After 24 years you will earn yourself and life will be comfortable.',
  'Ke-3':
    'According to Lal Kitab birth chart, Ketu is in house 3 in your chart. House 3 is Mercury\'s house and Ketu gives inauspicious effect here. You may have spine pain, boils or skin disease. Your brothers\' in-laws may have poor results. Some elder in your house should have grey hair. You should not keep your brother-in-law (sala) at home. You should not live in a south-facing house. You should not travel without reason.',
  'Ke-4':
    'According to Lal Kitab birth chart, Ketu is in house 4 in your chart. House 4 is Moon\'s house. Ketu\'s effect here is not good. You may have delay in having a son or less chance of progeny. Ketu reduces mother\'s happiness. You may have diabetes. You may face repeated shortage of money in business. Wearing earrings is auspicious for you. Taking advice from others may harm you. Your neighbour may also suffer loss.',
  'Ke-5':
    'According to Lal Kitab birth chart, Ketu is in house 5 in your chart. House 5 is Sun\'s own house and progeny is also seen from this house. Ketu is also a significator of son, so your chance of having a son increases. Keeping your conduct right will be auspicious for you. Your relationship with your wife will be good. If you have breathing trouble or asthma, you should take Jupiter\'s remedy.',
  'Ke-6':
    'According to Lal Kitab birth chart, Ketu is in house 6 in your chart. House 6 is Mercury\'s house and Ketu is debilitated here. You may have disease below the navel that is hard to detect. If your Jupiter is auspicious, your age will be beneficial for your business and progeny. You may have leg trouble or travel a lot, which is inauspicious for you and your wife. You can help your father, which will benefit you.',
  'Ke-7':
    'According to Lal Kitab birth chart, Ketu is in house 7 in your chart. House 7 is Venus\'s own house. Ketu and Venus are friends. Ketu gives more auspicious effect here. Making false promises or backing out may harm you. Your number of children may equal the number of your wife\'s siblings. At 24 years you have a yoga of wealth. You will not be troubled by enemies; they will leave on their own. You may get wealth even after the second child. There may be delay or obstacle in your marriage; you should do court marriage.',
  'Ke-8':
    'According to Lal Kitab birth chart, Ketu is in house 8 in your chart. House 8 is Mars\'s house and is also called the cremation ground. Your wife\'s health may remain poor. You may lose happiness of children. You may see someone\'s death before your own. Your children may come late. If you have one child before 34 and a second after 34, you may not get happiness of both. Your stomach may remain upset. You may have joint pain.',
  'Ke-9':
    'According to Lal Kitab birth chart, Ketu is in house 9 in your chart. House 9 is Jupiter\'s own house and Ketu considers Jupiter as guru, so Ketu gives good results here. You should do any big business only after taking advice from your father, grandfather or elders. Respecting your father is auspicious for you. Helping your grandson, nephew and brother-in-law from time to time is auspicious. You should keep gold at home so it increases. You should take your son\'s advice. You can give financial help to your maternal side.',
  'Ke-10':
    'According to Lal Kitab birth chart, Ketu is in house 10 in your chart. House 10 is Saturn\'s own house. If your brother harms you, forgive him; it will be auspicious for you. You should keep distance from other women. Keeping a dog will be auspicious for you. If Saturn is auspicious you may become a famous player. If your child is badly affected, before 45 years you should take a silver vessel in the shape of a pot, fill it with honey and bury it outside the house.',
  'Ke-11':
    'According to Lal Kitab birth chart, Ketu is in house 11 in your chart. House 11 is Saturn\'s own house. When your son is born, your mother\'s eyes and chest may be adversely affected. Even if you did not get ancestral wealth, you can build your own property. Your wife may have stillbirth. You may not be very courageous and may tend to postpone work. If Saturn does not give good results, your child and house will be badly affected.',
  'Ke-12':
    'According to Lal Kitab birth chart, Ketu is in house 12 in your chart. House 12 is influenced by Jupiter and is also the open sky. Ketu is exalted here, so Ketu\'s effect is good. You are someone who will progress in business. You will get more financial benefit from building house, travel-related work. Your son will be lucky for you. Your household life will be good. You may get property from father by inheritance. If dogs die at your place, you should keep a dog at home; it is auspicious for you.',
  'Ma-1':
    'According to Lal Kitab birth chart, Mars is in house 1 in your chart. Due to Mars in house 1 you will have brothers. You may have 32 teeth. You will progress after 28 years. Work related to iron, wood, machine etc. is auspicious. You will help your brothers and in-laws. Whatever you say about someone is likely to come true. If your Mars is inauspicious, Mars will start giving bad effects within 40 days of birth. You should work with your uncle (taya, chacha) or nephew. If you have a sister she will be like a queen. You should not take others\' troubles on your head.',
  'Ma-2':
    'According to Lal Kitab birth chart, Mars is in house 2 in your chart. You will be the eldest or behave like the elder brother. Being with brothers will be lucky for you. You will fulfill others\' needs. Even if you do not have a store of wealth, both your in-laws and home will be prosperous. Money will be arranged when needed. Electrical work will be beneficial for you. You will be religious. You may have stomach disease in childhood.',
  'Ma-3':
    'According to Lal Kitab birth chart, Mars is in house 3 in your chart. You are of a brave nature. You can do any big work on the strength of your might and self-confidence. No one can fool you. You get angry very quickly. Your mind is fickle. If your Mars is not auspicious, your nature will be like a zoo lion—a strong person in a cage. Your in-laws may be wealthier than you. You will have brothers and sisters. You help friends and visitors from time to time. If your head is small and stomach bloated, you may have blood-related disease.',
  'Ma-4':
    'According to Lal Kitab birth chart, Mars is in house 4 in your chart. No one can trouble you for any reason; if they do, you can reply well. If you have a desire for revenge, you will be at a loss. You may be heavy on your mother, mother-in-law, wife or grandmother. Kikar or berry tree in your house is inauspicious for you. If there is a sweet shop or roasting kiln near your house, you will be at a loss. A south-facing house is also harmful for you. When leaving home, kitchen on the right and water tap on the left is harmful for you. If peepal tree shade falls on your house, that too is harmful.',
  'Ma-5':
    'According to Lal Kitab birth chart, Mars is in house 5 in your chart. This house is Sun\'s own house. Sun and Mars are close friends, so Mars gives excellent results here. As your age increases your wealth will increase. If you live in your ancestral home you will keep getting happiness of children. There may be more doctors among your relatives. You will have no shortage of money. Your progress will start from the time of your child\'s birth. Due to your auspicious Mars, the money you earn will also give happiness to your children. Keeping water near your head at night will benefit you. Water a plant in the morning. You are of a calm nature.',
  'Ma-6':
    'According to Lal Kitab birth chart, Mars is in house 6 in your chart. House 6 is influenced by Mercury and Ketu and both are enemies of Mars, so Mars gives its bad effect. Celebrating when you have a child will be harmful for you. Your first son may not survive. You will get happiness of children at 34 years. You can earn money by the strength of your speech. If you do pen work—reading and writing—it is auspicious for you. Your brothers may be less wealthy than you; helping them financially will be auspicious for you. Your maternal uncle, wife and children\'s health may deteriorate. You can see your three generations with your own eyes.',
  'Ma-7':
    'According to Lal Kitab birth chart, Mars is in house 7 in your chart. If Mars is in house 7 you should worship Lord Vishnu. Serving your nephew is auspicious for you. You are someone who does religious deeds and is useful in trouble. Business of astrology is auspicious for you. You are a man of justice. If Mars is bad, your domestic life may be spoiled. If there is a well near your house it is inauspicious for you. If your widowed sister stays with you, you will lack children. You may have blood-related disorders. You will keep getting both profit and loss in life. A broad-leaved tree is inauspicious for you. Consumption of meat and liquor is auspicious for you. Do not break the stairs in the house and rebuild again and again.',
  'Ma-8':
    'According to Lal Kitab birth chart, Mars is in house 8 in your chart. Mars is not auspicious in house 8. Here Mars is also called the noose of death. You will not get happiness of women. You should set up a dark closet in your house with no light. You should avoid the curse of a widowed woman. Your eyesight may become weak. You should ensure your uncles, brothers and nephews are not suffering again and again. You will get less happiness from your mother. You should avoid anger. You should wear a silver chain until 28 years. A south-facing house is not auspicious for you. If you have built a furnace at home, wash away all the soil around it with water and put new soil in the house.',
  'Ma-9':
    'According to Lal Kitab birth chart, Mars is in house 9 in your chart. House 9 is Jupiter\'s own house and Jupiter is Mars\'s friend, so Mars has good effect here. If you are a believer you will get good results; if you are an atheist you will get bad results. Your sister-in-law (bhabhi) is lucky for your fortune. If you live with your brothers and work with them it will be auspicious for you. Mars-related businesses like hotel, sweets, food and drink where fire is used are beneficial for you. You are likely to get land and property from your father. From 13 years your parents\' financial condition will improve and by 28 you will have your own wealth.',
  'Ma-10':
    'According to Lal Kitab birth chart, Mars is in house 10 in your chart. Mars is exalted in house 10. You can be a benefactor of your family. There must have been economic development in the family after your birth. You are someone who builds land and property on your own. If you have an elder brother you will definitely have a son. You are in good health. You are of a brave nature. Your family and hard work will increase day by day. You are the owner of a good household. You will keep getting happiness of wife and children. If you sell gold it is inauspicious for you as it will have a bad effect on you. You will benefit from dark or one-eyed people if you help them.',
  'Ma-11':
    'According to Lal Kitab birth chart, Mars is in house 11 in your chart. House 11 is Saturn\'s house but it is also influenced by Jupiter, so Mars gives auspicious results here. In this house Mars is called a lion raised on milk. Your spiritual power will be very high. Raising and serving animals is beneficial for you. You always judge. If Mars becomes inauspicious in this house the native loses money; the native and the native\'s son both suffer. Mars\'s influence remains till 45 years. You keep getting help from your sister\'s in-laws, your in-laws and your mother\'s in-laws. If you do a job you get a high position; if you do business you get good profit. The 28th year is auspicious for you. Your brother-in-law, brother-in-law and grandson are all auspicious for you.',
  'Ma-12':
    'According to Lal Kitab birth chart, Mars is in house 12 in your chart. Mars gives its good effect in house 12 because this house is Jupiter\'s and Mars and Jupiter are friends. You may be hot-tempered and you are late in listening to others. If you serve your Guru it will be auspicious for you. You are likely to have a son at 24 or 28 years, which will be very auspicious for you. You can be the owner of good wealth. If Mars is auspicious the biggest trouble coming on you will be avoided. If your brother comes to your house, definitely give him milk. Taking silver or rice in donation from your brother will be auspicious for you. Feeding sweets to people will be auspicious for you.',
  'Me-1':
    'According to Lal Kitab birth chart, Mercury is in house 1 in your chart. House 1 is influenced by Sun and Mars and Mercury lives in it like a tenant. You may face infamy due to Mercury in house 1. You should not consume meat and alcohol. If you work in one place instead of roaming around you will get more benefit. Your wife may be from a rich family. If you earn through medicine and doctor\'s work it will not give you auspicious results. Consumption of alcohol, meat and fish will have a bad effect on you.',
  'Me-4':
    'According to Lal Kitab birth chart, Mercury is in house 4 in your chart. House 4 is Moon\'s own house. In this house Mercury gives good results for its significations. Your income will be good and will keep increasing day by day. If your mother\'s health is bad it means Mercury is giving inauspicious results. Taking Jupiter\'s remedy here will be auspicious for you. If Mercury is malefic, all house members and domestic life can be affected. If you take someone\'s advice it can also be the cause of your ruin.',
  'Me-5':
    'According to Lal Kitab birth chart, Mercury is in house 5 in your chart. House 5 is Sun\'s own house. Mercury\'s effect here is good. Any word that comes out of the native\'s mouth about someone will surely come true. If you serve the cow it will be auspicious for you, your wife and children. After 34 years your fortune will rise. You will get good results in both business and family. If you fool someone you will harm yourself. You are a person of character whose fruits you will fully reap. You will not be short of money.',
  'Me-6':
    'According to Lal Kitab birth chart, Mercury is in house 6 in your chart. House 6 is Mercury\'s own sign and Mercury is exalted here. If you want to earn from agricultural land it will be auspicious for you. Paper work or printing on paper is auspicious for you. North direction is not auspicious for you. You will benefit from doing business with countries across the sea. By 34 years your mother\'s health will be badly affected. Your wife may be from a well-to-do family. If your house is north-facing you will suffer. You should not marry your daughter in the north direction. Before any special work, giving flowers to your daughter or a girl will be auspicious for you. Giving a bouquet to someone on their wedding or birthday will also be auspicious for you.',
  'Me-7':
    'According to Lal Kitab birth chart, Mercury is in house 7 in your chart. Mercury in house 7 gives higher education to a person. If you turn your pen into a sword you will get benefit. You will do any work with your own hands—carpenter\'s work etc. will be auspicious for you. You will help all family members from time to time. You will win in litigation. You are more likely to have a love marriage. Your childhood will be spent badly. If your Mercury is weak, the female side—your sister, aunt, daughter and sister-in-law—will be badly affected.',
  'Me-9':
    'According to Lal Kitab birth chart, Mercury is in house 9 in your chart. This house is Jupiter\'s own house. But Mercury\'s effect here is not good. The native\'s mind does not get peace here and allegations are made without reason. In this house Mercury is also called the king of cowries. A person with Mercury in house 9 also gives less respect to his father. If you keep ashes, amulet or any device with you it will have a bad effect. Getting nose pierced will be auspicious for you. Wearing silver is auspicious for you. If you keep an amulet in the house, the bad effect will be visible on you within 43 days. If you have trouble speaking you may also have trouble having children.',
  'Me-10':
    'According to Lal Kitab birth chart, Mercury is in house 10 in your chart. If Mercury is in house 10 such a person flatters the person in front to get his work done; he can go to any extent. Such a person is sweet-talking and gets his work done by trapping others—i.e. deceives people. You can also earn from sea travel. You can be proficient in any task. If you are shameless by nature it is inauspicious for you. If you eat delicious food it is harmful for you. Your age from 36 to 58 will be slow. If you consume alcohol it will be like snake venom for you.',
  'Me-11':
    'According to Lal Kitab birth chart, Mercury is in house 11 in your chart. Your fortune will rise only after 34 years. You can be proficient in any task. If you do not respect others it will be bad for you. You can earn so much when the time comes that buying diamonds and pearls will be like buying peanuts. Do not do foolish things. Take someone\'s advice otherwise you will lose money, lose fame and mind will be restless. If Mercury\'s result is slow for you, whatever work you are doing will be at a loss and everyone will keep calling you names. Your sister will go to a wealthier family than you but she is likely to be widowed or divorced from her husband.',
  'Me-12':
    'According to Lal Kitab birth chart, Mercury is in house 12 in your chart. Mercury is debilitated here. Such a person is the master of sorrows—seeing which even the sky weeps. Mercury gives inauspicious results in the 12th. If you stay at your sister\'s or aunt\'s house your sorrow will increase further. If you live at your in-laws\' house it will be auspicious for you. You keep losing money. Such a person is a liar and goes back on the promises he makes. If you do speculation, alcohol, paper or printing work you will get bad results and much defamation. You may have nerve disease. You can be someone who works in a hurry and without thinking in every task.',
  'Mo-1':
    'According to Lal Kitab birth chart, Moon is in house 1 in your chart. You have long life. As long as your mother is alive you will have no lack of wealth. You should avoid water. You may be a sociable person; keeping your sister-in-law (sali) at home and using Mercury-related items will be harmful for you. You should drink water in a silver vessel. You should keep taking your mother\'s blessings or else your mother\'s health will deteriorate. You should not build a house until 24 years. Do not do silver business. You should fix copper nails in the four legs of your bed. Taking silver from your mother\'s hand will be beneficial for you.',
  'Mo-2':
    'According to Lal Kitab birth chart, Moon is in house 2 in your chart. Moon in this house is considered excellent because Moon is exalted in sign number 2. You should get a share in parental property. You should not build a temple at home and should not ring bells or gongs. If you were born in the bright fortnight (shukla paksha) your old age will be good; if born in the dark fortnight (krishna paksha) your childhood will be good. Burying silver at home will be auspicious for you. If some part of your house has raw earthen floor it will be auspicious and you can be more successful.',
  'Mo-3':
    'According to Lal Kitab birth chart, Moon is in house 3 in your chart. So you respect women at home and this is very auspicious for your fortune to rise. Love between you and your wife and serving elders is also beneficial. Even if you were born in a poor family you will have wealth and respect. There will be no theft in your house. Your relationship with brothers will be good and women\'s position will also be good. Cattle business can also be beneficial for you. You should not take money from in-laws at your daughter\'s marriage. Serve milk or water to guests who come home. Kanyadaan is auspicious for you. Donating wheat at a girl\'s birth is auspicious for you. Conjunction of Moon and Saturn here creates a poison yoga.',
  'Mo-4':
    'According to Lal Kitab birth chart, Moon is in house 4 in your chart. So you should serve guests at home milk instead of water. You will have no lack of wealth. You can be a famous person. You may have farmland, milch animals and fruit trees or a garden. You will get full happiness of mother, father, wife and son. If you were born in the dark fortnight your childhood is good; if in the bright fortnight your old age will be good. Keeping milk in an earthen vessel at home will give you success.',
  'Mo-5':
    'According to Lal Kitab birth chart, Moon is in house 5 in your chart. House 5 is Sun\'s own house and also the significator of sons. If you serve the public it will have a good effect on your progeny. You are a diamond-like shining person. You are kind-hearted. You do not bow before anyone. Whoever you stand with will win. You may get benefit from government work. You will be at the forefront in doing justice to others.',
  'Mo-6':
    'According to Lal Kitab birth chart, Moon is in house 6 in your chart. Moon does not give auspicious results here. Only if there is an auspicious planet in house 2 can Moon give good results. If you do bad deeds Moon will give bad results. Donating water is like death for you. Drinking milk at night is harmful for you. Your wife may have trouble at the time of childbirth. Installing a water hand-pump at a hospital or cremation ground can be auspicious for you. If Sun is in house 12, your or your wife\'s eyes may be affected. You will get less happiness from mother. Consuming curd and paneer is good for you.',
  'Mo-7':
    'According to Lal Kitab birth chart, Moon is in house 7 in your chart. Moon in this house is called the incarnation of Lakshmi. Even if you were born in a poor family you will have no trouble of gold, silver or house. You do not pay special attention to your sister or daughter. You can be skilled in astrology which is auspicious for you. Your death will be at your own home. Milk business will weigh heavily on your progeny. At the time of your marriage you should take milk, silver and pearls etc. from in-laws.',
  'Mo-8':
    'According to Lal Kitab birth chart, Moon is in house 8 in your chart. House 8 is also called the cremation ground and is under the influence of Saturn and Mars. If there is a pond or well near your house your fortune may not support you. You are a person who lives in imagination. You are troubled by fear of water. There is a chance of your eyesight weakening. There will be lack of wealth until 34 years. You may get less happiness of land and of women. You will get less happiness from your wife. Arranging water at the cremation ground will be auspicious for you. Your source of income may also be black money. You will definitely get happiness of a son. You may lack strength in the body. If there is a well in your house it may have a bad effect on your progeny.',
  'Mo-9':
    'According to Lal Kitab birth chart, Moon is in house 9 in your chart. Moon in house 9 is also considered a significator of land and property. So you will not lack land. You will be skilled in mathematics and science. You are a pilgrim. You are someone who does good for all. You may get your parents\' happiness for a long age. If you have an elder brother you will not get his support. You will have no lack of income. You may have a liking for music.',
  'Mo-10':
    'According to Lal Kitab birth chart, Moon is in house 10 in your chart. House 10 is Saturn\'s house. Your age can be long. You may have a good amount of wealth. You can do medicine-related work. You should not give liquid medicine to a sick person. If your mother\'s health is bad you should go to the temple daily. You may get full happiness of your parents. A widowed woman can cause you loss. Your in-laws\' financial condition may be good. You will get no benefit from milch animals. Machine and wood work can be auspicious for you. If you have a relationship with another woman it will be harmful for you.',
  'Mo-11':
    'According to Lal Kitab birth chart, Moon is in house 11 in your chart. House 11 is Saturn\'s own house. Moon gives only its bad effect here—i.e. a poison dosha yoga is formed in this house. In annual transit if Moon is in house 1 or 2 it gives excellent results. Taking or giving kanyadaan after 12 midnight is auspicious for you. Your ability to have a son is less. You will get less support from your mother or her health will remain poor. You should not do toy business for children. You should not do worship at night. If your Moon is good you can become a high official. If you do good deeds you will get good results; if you do bad deeds you will get bad results.',
  'Mo-12':
    'According to Lal Kitab birth chart, Moon is in house 12 in your chart. House 12 is Jupiter\'s own house but Rahu also has influence here, so Moon cannot give auspicious results. If you receive wealth from your parents, do not take it in your name but in your wife\'s and son\'s name. You will benefit greatly from wealth earned by your own hands. Troubles will keep coming upon you. You will not sleep well at night. You may have scalp skin disease. You can be lazy. After 48 years of age Moon\'s results will become auspicious. You or your wife may have disorder in one eye.',
  'Ra-1':
    'According to Lal Kitab birth chart, Rahu is in house 1 in your chart. House 1 is influenced by Mars and Sun; Rahu\'s effect is seen as less here. You should not take electrical items and black clothes etc. from in-laws at the time of marriage or after. You should keep donating wheat etc. At the time of your birth there may have been rain or storm or power cut for some time. There is a possibility that the house in front of you does not have a male child. You may be someone who is dishonest with the person in front. You should not do electrical work etc. If you keep changing jobs your wife will earn less.',
  'Ra-2':
    'According to Lal Kitab birth chart, Rahu is in house 2 in your chart. House 2 is under Jupiter and Venus, so either your situation will be good or very bad. If you get happiness of women then wealth will be less; if you get wealth then happiness of women will be less. Fear of theft of wealth will always trouble you. Others will obey you and respect you. You will keep getting both good and bad results in life. You are someone who takes from others for free but will not give anything to others. If your nails are getting bad it is an inauspicious sign. You may have paralysis and mental disease.',
  'Ra-3':
    'According to Lal Kitab birth chart, Rahu is in house 3 in your chart. House 3 is under Mars and Mercury; so you are a powerful person—your enemies cannot stand before you. Rahu is good for itself here. The dreams you see come true within 2 years. If you face your enemy with a pen instead of a sword it will be more effective. You can leave your father\'s property. If Mars is also in house 3, Rahu\'s auspicious effect will increase further. Your children will also be wealthy. Your wife will keep getting wealth and happiness of children. Your sister\'s domestic life may have ups and downs.',
  'Ra-4':
    'According to Lal Kitab birth chart, Rahu is in house 4 in your chart. House 4 is influenced by Moon. So one of your houses or one vehicle will sell at a low price. You are a person who cooks imaginary dishes. You are heavy on your maternal grandfather and maternal uncle. You will keep helping your relatives. After 24 years you have yoga of marriage and wealth. You should not make a tank that collects water underground in your house. You should not fill storage of coal sacks. You should not make an oven underground. You should not change your house\'s roof.',
  'Ra-5':
    'According to Lal Kitab birth chart, Rahu is in house 5 in your chart. House 5 is Sun\'s own house. Progeny is also seen from house 5. So your wife\'s miscarriage will definitely happen once. Your education will also have obstacles. There is a possibility of your father\'s death at 21 or 42 years of age. You should not celebrate at your child\'s birth; it is inauspicious for your progeny. Keeping a solid silver elephant at home will be auspicious for you.',
  'Ra-6':
    'According to Lal Kitab birth chart, Rahu is in house 6 in your chart. House 6 is Rahu\'s own house, so Rahu\'s inauspicious effect is seen here. So you cannot be troubled by disease, debt and enemy. You will keep getting promotion in business or job but you will keep getting transferred. If someone stops you before going to any work, your Rahu will start giving inauspicious results. There is a possibility of a mole near your navel. Your in-laws\' financial condition and comfort may also be less.',
  'Ra-7':
    'According to Lal Kitab birth chart, Rahu is in house 7 in your chart. House 7 is Venus\'s own house, so when Rahu is here the native\'s family life does not go well—either the native\'s wife remains ill, or the native may get divorced, or the native\'s wife is older than the native. The person suffers loss from electrical work. If marriage happens at 21 years there is a possibility of divorce or death. Due to Rahu in house 7 there can also be financial loss. Keeping a dog here is harmful for the native.',
  'Ra-8':
    'According to Lal Kitab birth chart, Rahu is in house 8 in your chart. House 8 is Mars\'s own house. Here Rahu gives its auspicious effect more. Obstacles definitely come in the native\'s work. There is also loss in business. If there is a tall dark or one-eyed person in the family, Rahu\'s effect gets worse. Someone in the house may have asthma. The native also has stomach disease. If the native earns money dishonestly, the native suffers 8 times the loss.',
  'Ra-9':
    'According to Lal Kitab birth chart, Rahu is in house 9 in your chart. House 9 is Jupiter\'s own house and Rahu is the significator of smoke. So the native does not have faith in religion. The native has no special respect in society. Due to Rahu in house 9 the native may also have loss of progeny. The native should get another dog as soon as one dog dies. This karma can continue 11 times. Keeping a dog will increase the native\'s children\'s age. The native should live with his ancestral family and keep good relations with in-laws.',
  'Ra-10':
    'According to Lal Kitab birth chart, Rahu is in house 10 in your chart. House 10 is Saturn\'s own house. So you can be a good businessman. You can be in a good position in government job. Your age will be long but your mother\'s health may remain bad. If you are of a miserly nature it will be inauspicious for you. You may have headache. Sometimes Rahu\'s strong effect is also seen on the native\'s wealth.',
  'Ra-11':
    'According to Lal Kitab birth chart, Rahu is in house 11 in your chart. House 11 is Saturn\'s own house and Jupiter also influences this house. Your father or grandfather may suffer loss. After your birth your father\'s income will be affected. You do your work with attention and cleverness. Your friends\' company also remains but you will suffer from doing mean work and getting wealth from mean people. It is not possible for your father, you and your son to be together.',
  'Ra-12':
    'According to Lal Kitab birth chart, Rahu is in house 12 in your chart. House 12 is Jupiter\'s own house; rest and moksha are also found here. Jupiter and Rahu are enemies. Due to Rahu in house 12 you do not get sleep or rest either. You can be someone who studies well. Due to Rahu you may also have yoga of litigation or jail. Your expenses can be high. You may also face repeated trouble in respect. You may have to spend on your daughter or sister or pay the loan taken by them.',
  'Sa-1':
    'According to Lal Kitab birth chart, Saturn is in house 1 in your chart. House 1 is Mars\'s house; this house is under Sun and Mars. Sun is Saturn\'s enemy, so Saturn\'s effect is not good. The native\'s education has been seen to have obstacles. If Saturn\'s enemy planets are in houses 4, 7, 10, Saturn gets all the house\'s things auctioned. With Saturn in house 1 the person starts stealing etc. and deceiving others. Due to Saturn in house 1 the person\'s education, wife, mother and wealth are all badly affected. Such a person\'s government work also has obstacles. Such a person\'s eyesight also becomes weak quickly. In short, Saturn\'s effect in house 1 will remain dull.',
  'Sa-2':
    'According to Lal Kitab birth chart, Saturn is in house 2 in your chart. House 2 is influenced by Venus. Venus is Saturn\'s friend so Saturn\'s effect here remains okay. When Mars is bad the native remains ill till 31 years. Such a person also gives bad effect to his in-laws. If the native gambles it is bad for him. Such a person thinks of leaving worldly life and taking sanyas—i.e. thinks what will be gained by doing any work. When such a person buys house, machine, car etc. his in-laws are badly affected.',
  'Sa-3':
    'According to Lal Kitab birth chart, Saturn is in house 3 in your chart. House 3 is Mercury\'s own house and Mercury is Saturn\'s friend. When such a person\'s houses get built they get excellent results. Such natives are healthy. They have good intelligence in conversation and do all work thoughtfully. But they are ahead in spending. Such a person\'s keeping a dog also gives auspicious results. But a south-facing house gives inauspicious results. If there is any stone or electric pole in front of the house there is loss. The native should make a room in his house where light does not go; it will be auspicious for his wealth.',
  'Sa-4':
    'According to Lal Kitab birth chart, Saturn is in house 4 in your chart. House 4 is Moon\'s own house and Saturn creates poison yoga here. If the person falls ill repeatedly he should take pills. He should not take liquid medicine. Such a person should not use alcohol, meat and egg. Drinking milk at night is like drinking poison. Such a person does not suffer from drinking alcohol. If Moon is auspicious the person will get his parents\' company for long and household happiness for long. Such a person is not auspicious for his maternal grandfather and uncle. If such a person earns from bad earnings of women it is inauspicious for him. Serving labourers gives auspicious results for such a native.',
  'Sa-5':
    'According to Lal Kitab birth chart, Saturn is in house 5 in your chart. House 5 is Sun\'s own house. Sun and Saturn are enemies, so only Saturn\'s bad effect is seen. You try to get your way with others in every situation. You have a bit too much pride. If you do not use your brain you will have loss in every work. If you build a house it may badly affect your children; so if you build, build in your child\'s name or you should build house only after 48 years of age. You should not celebrate your son\'s birthday and should distribute salty instead of sweet. Keeping a dog will be auspicious for you.',
  'Sa-6':
    'According to Lal Kitab birth chart, Saturn is in house 6 in your chart. House 6 is Mercury\'s house and is under Ketu\'s influence. Saturn is friend to both so Saturn gives less bad results here. You should marry only after 28 years of age. You must have a son. Your behaviour with the eldest son may not be good. But he will be the one to help in your last time. Your younger brother may be your enemy. If only sons are born to you, your parents\' health and their financial condition will be positively affected. You may also get full happiness of wife. If your shoes get lost you will face trouble in police, court or government work. You should use less leather items like purse, belt and shoes.',
  'Sa-7':
    'According to Lal Kitab birth chart, Saturn is in house 7 in your chart. House 7 is Venus\'s own house. Saturn is exalted here so Saturn gives good results only. If you keep good relations with your wife it will be beneficial for you and your money. You should not work in partnership with anyone. You have yoga of getting land and property by inheritance. If Mars is auspicious your income can be lakhs per month. If you have less body hair, Saturn\'s effect here may be reversed. If you keep contact with another woman it will be inauspicious for your wife. If you consume alcohol you will have financial loss. Working at night is auspicious for you.',
  'Sa-8':
    'According to Lal Kitab birth chart, Saturn is in house 8 in your chart. House 8 is Mars\'s house and Saturn does the work of executioner here. You should not consume egg, meat and alcohol. If you consume these, Saturn\'s bad effect will fall. Fear of punishment by the government will keep troubling you. If you have more body hair you may suffer poverty for life. If any other planet is also with Saturn in house 8, you will get success only after that many people\'s deaths, or Saturn will keep harming whichever planet is with Saturn. You will also have fear of your eyes getting bad. You have yoga of injury from a weapon till 27 years of age.',
  'Sa-9':
    'According to Lal Kitab birth chart, Saturn is in house 9 in your chart. House 9 is Jupiter\'s own house. Saturn\'s excellent results are seen here. You can be a charitable person. Your house may be at the corner or there will be empty space in front and behind your house. You can build three houses but as soon as you build the fourth you will start facing trouble. You should not keep broken wood at home. Your birth may be in a large family. Your education can be good. Your income can be good and you will never take loan from anyone. You will suffer loss from Saturn\'s items like factory work, shoe work and wood work.',
  'Sa-10':
    'According to Lal Kitab birth chart, Saturn is in house 10 in your chart. House 10 is Saturn\'s own house and Saturn gives good results only here. You will keep getting benefit from land and property. You are someone who does religious work but you are someone who takes others\' troubles on your neck. If you do any work that requires going from one city to another, that work will be auspicious for you. Drinking alcohol is harmful for you. You should not build a new house before 48 years or your income will stop and you will suffer much loss. Your fortune will rise after 27 years. Your in-laws\' financial condition can be good.',
  'Sa-11':
    'According to Lal Kitab birth chart, Saturn is in house 11 in your chart. House 11 is Saturn\'s own fixed house and this house also shows the person\'s income. With Saturn in this house the position is like a judge giving verdict. You have yoga of getting wealth and property from your father. You also have yoga of having a son. You can earn money by your cleverness and by involving others in your talks. If you live in a south-facing house it is not auspicious for you. Egg, meat and alcohol will give you bad effect. If you have to build a house you should build between 48 and 55 years of age otherwise you will suffer loss.',
  'Sa-12':
    'According to Lal Kitab birth chart, Saturn is in house 12 in your chart. If your hair is falling from your head you will not lack wealth and property. You have full yoga of your house being built. You can be a good businessman. But you also cheat the person in front. You do not care about money. You can be troublesome for your mother and your father\'s expenses will increase a lot after your birth. If Sun is in house 6 you will not get wife\'s happiness. You must make a dark closet inside the house. If you consume alcohol etc. it will have bad effect on your eyes and health. Do not tell your secrets to anyone. You are always eager to do big work.',
  'Su-1':
    'According to Lal Kitab birth chart, Sun is in house 1 in your chart. So you will have long life. Your hair will be less. You may have eye disease. Your nature will be of a fierce tendency. You should stay away from flirting. The number of your brothers and sisters will be less. You will serve your father. You will keep getting happiness of women and children. If you put 25% of your earnings in religious work it will be very good for you.',
  'Su-2':
    'According to Lal Kitab birth chart, Sun is in house 2 in your chart. So you are the master of your own strength—you do your work yourself. If you are a lawyer or surgeon you will achieve more success. You will be helpful to others. You will attain fame. You will definitely get the pleasure of conveyance at home. You should not quarrel with the woman of the house; quarrelling will have a bad effect.',
  'Su-3':
    'According to Lal Kitab birth chart, Sun is in house 3 in your chart. So you are the king of wealth. You earn and eat by your own hard work. Your interest may also be in astrology; it is an auspicious work for you. You will be the eldest among brothers or great by nature. Even if you are born in a poor family you will be wealthy. Due to Sun in house 3 your neighbours may be in distress.',
  'Su-4':
    'According to Lal Kitab birth chart, Sun is in house 4 in your chart. So you will keep adding wealth but will not be able to use it; but your grandchildren will be crorepatis. Due to Sun in house 4 you will benefit from the house where Moon is. You can leave your ancestral place and make your new residence far away. Your mother or sister may have trouble. You may have eye trouble.',
  'Su-5':
    'According to Lal Kitab birth chart, Sun is in house 5 in your chart, which is Sun\'s own house. If you build a kitchen in the east of your house it can be very auspicious for you. You are good in studies and have more anger. Your stomach gets upset quickly. You get help from the government quickly. You are charitable and take everyone along. You have yoga of getting a son. Your old age will be spent well.',
  'Su-6':
    'According to Lal Kitab birth chart, Sun is in house 6 in your chart. So you will not run after wealth. You can be very angry. It has been seen that Sun in house 6 has only bad effect. It is good if you change your work and job before the first son is born. If you break the west wall of your house for light you can be ruined. Your birth may also have been at your maternal grandfather\'s house. You will not get full rest at night. Eyesight may become weak in old age. Your fortune will rise after 22 years. You may be troubled by litigation.',
  'Su-7':
    'According to Lal Kitab birth chart, Sun is in house 7 in your chart. Your in-laws\' source of income will not be good. You are not stingy by nature and giving donation will be auspicious for you. You will keep travelling and working in other countries all your life but you will die at your home. If your Sun is very bad you may be born dumb or mad. You can be very angry and may have a habit of eating more salt which will have a bad effect on you—so reduce salt intake.',
  'Su-8':
    'According to Lal Kitab birth chart, Sun is in house 8 in your chart. So you are ascetic and of a true nature. No one will die in front of you in your house—you will not see anyone\'s death in your house with your own eyes. You may be harmed by poisonous animals. Your own death will also be sudden. You are angry and a recipient of secret knowledge. You will be attracted to women. You should not live in a south-facing house. You may be the eldest in the house or if you go against your elder brother it will have a bad effect. Your servants and women can be unfaithful.',
  'Su-9':
    'According to Lal Kitab birth chart, Sun is in house 9 in your chart. Here Sun is very powerful because it is Jupiter\'s house. You will serve your father and grandfather. You will get full happiness of vehicles etc. You will have the power to cure others\' disease. You will do a lot for your family but will not ask for anything in return. Even if you are born in a poor family you can be someone who does good to the whole family on your own.',
  'Su-10':
    'According to Lal Kitab birth chart, Sun is in house 10 in your chart. So you may also be a bit suspicious by nature because house 10 is Saturn\'s house. So Sun will reduce its results here. You can be the owner of good health and good property. You will always be confused. You should not make a skylight in the west direction of your house. Your neighbour may be dark or one-eyed. You may suffer from anger. You should not wear blue clothes. You should wear light-coloured clothes. You can wear sherwani or white turban.',
  'Su-11':
    'According to Lal Kitab birth chart, Sun is in house 11 in your chart, which is Saturn\'s own house, so you should not eat alcohol, meat and egg. House 11 is also called the court and due to Sun in house 11 you will suffer a lot from fights. You should not take care of others\' property. You may have many snake dreams. You must not bear false witness.',
  'Su-12':
    'According to Lal Kitab birth chart, Sun is in house 12 in your chart. So you should not take others\' trouble on yourself unnecessarily. You must be getting good sleep at night. If you do not work with your own hands and get others to work it will be auspicious for you. Your eyes may be weak or there may be some defect in your eyes. You should live in a house that has a courtyard. You should not partner with your uncle (chacha, tau) or brother-in-law (sala).',
  'Ve-1':
    'According to Lal Kitab birth chart, Venus is in house 1 in your chart. Due to Venus in house 1 you are a working person and you also get benefit from the government. You will get full happiness of conveyance. Your income will be good but you will not be able to save much. House 1 is influenced by Sun and Mars and Venus is enemy of both, so you or your wife may have complaint of long illness. You are quick to be attracted to women and give everything for her. Having intercourse during the day is harmful for you. Getting married at 25 years of age is not auspicious for you. Your chance of losing a case is low. You may have relations with many women which will have a bad effect on you.',
  'Ve-2':
    'According to Lal Kitab birth chart, Venus is in house 2 in your chart. House 2 is Venus\'s own house. You will keep earning continuously from the day you start earning till 60 years. You may be of a romantic nature. Speaking ill of anyone is harmful for you. You will get full enjoyment of progeny and luxury. Your son and brothers\' situation may become good because of you. If Saturn is in house 9 Venus\'s result will double. If your house is gomukhi it will be harmful for you. It is often found that due to Venus in house 2 your wife will not be happy with you. Gold work is harmful for you.',
  'Ve-3':
    'According to Lal Kitab birth chart, Venus is in house 3 in your chart. House 3 is under Mars and Mercury. If you follow your wife\'s advice it will be beneficial for you. You can earn more wealth with less effort. If you do pilgrimage till 34 years of age it will be auspicious for you. If you do not get sleep till 34 years of age you should take Mercury\'s remedy. You have yoga of getting your parents\' happiness for a long time.',
  'Ve-4':
    'According to Lal Kitab birth chart, Venus is in house 4 in your chart. Due to Venus in house 4 you will travel a lot which will benefit you. Your maternal uncle\'s family may be badly affected. You will have spiritual inclination. Some power may reside in you. If you have constant dispute with your wife you should remarry your wife and call her by two names at home. You should never close a well and build a house on it. Your 4 years after marriage will be spent very well. If you flatter someone else it will be inauspicious for you. Do not have relations with anyone other than your wife—it can also be the cause of ruin. If Jupiter is in house 1 your maternal uncle, your mother and your wife will be badly affected.',
  'Ve-5':
    'According to Lal Kitab birth chart, Venus is in house 5 in your chart. House 5 is Sun\'s own house. Due to Venus in house 5 your wife\'s health may be bad. You are a learned person and no enemy can stand before you. You should not have relations with any woman other than your wife otherwise your fortune will be spoiled. As long as your wife is with you you will not face any obstacle in any work. If you behave like a saint with everyone your fortune will shine like a diamond. If you keep your conduct right your and your wife\'s health will be fine. Serving cow and mother will be auspicious for you.',
  'Ve-6':
    'According to Lal Kitab birth chart, Venus is in house 6 in your chart. House 6 is influenced by Mercury and Ketu. If your wife dresses well there will be no shortage of wealth in your house. Your wife should keep long hair and wearing a gold clip will give more happiness. Your marriage may be delayed. Your education may have obstacles. You will get less happiness from father. You are the owner of a healthy body. Your old age will also be spent well. Your wife should not walk barefoot on the ground at home. Your children may not listen to you. If your wife does not have an elder brother it is auspicious for you. If you do work related to women\'s use you may not get success. You can be a good person who gives knowledge.',
  'Ve-7':
    'According to Lal Kitab birth chart, Venus is in house 7 in your chart. House 7 is Venus\'s own house and house 7 is also the house of marriage. If Venus is in house 7 you should not do business in partnership with any in-law. Your wife should not wear blue clothes. You keep going far from home again and again for business. So you will get less family happiness. If you keep relations with another woman it can cause ruin. Your wife may be more beautiful and sweeter natured than you. After marriage your fortune will start shining. You have more possibility of loss in business or theft at home. If light comes from your roof your wife\'s health may be badly affected.',
  'Ve-8':
    'According to Lal Kitab birth chart, Venus is in house 8 in your chart. House 8 is also called the cremation ground so planets do not give good results here. Venus is used to see the native\'s wife so due to Venus in house 8 the native\'s wife is of an angry and useless nature. The native\'s domestic life is bad and he himself remains troubled. If the native troubles his wife the native himself remains troubled. The native should marry only after 25 years. The native is also skilled in secret knowledge but the person remains in debt. The native can also be inauspicious for his in-laws. Taking anyone\'s guarantee for the native can create trouble.',
  'Ve-9':
    'According to Lal Kitab birth chart, Venus is in house 9 in your chart. House 9 is Jupiter\'s own house and Venus and Jupiter are enemies. So a bad situation is created. Such a person has to crave for bread even after having money. If the native\'s marriage happens at 25 years or he does any Venus-related work the native will only suffer loss. The native gets less happiness of brother, kin and wife. If the native lives with his wife\'s maternal family it will be inauspicious for him. At 17 years of age the native may get the habit of intoxication and the native\'s wife\'s health also remains bad due to diseases.',
  'Ve-10':
    'According to Lal Kitab birth chart, Venus is in house 10 in your chart. House 10 is Saturn\'s house and Saturn and Venus are not enemies, so the person gets benefit. If you do Saturn-related work you will benefit. Wherever you go for work, taking your wife along can double the benefit. You may be suspicious. You may be clever and of a cunning mind. Your wife\'s health may remain good. You should keep the west wall raw or keeping some part raw on the west side will benefit you. If you become characterless your children will suffer. If your health is not good you should donate to a Kapila cow; it will be auspicious for you.',
  'Ve-11':
    'According to Lal Kitab birth chart, Venus is in house 11 in your chart. You are of a simple nature. You run after money a lot. You may be someone who does secret work. You keep changing your rules with time. If your wife controls your money your business can be ruined. You may get a son late. If your wife has three brothers, taking their help will be auspicious for you. Your daughter will be born with her own fortune and she will not lack wealth. If your children\'s health remains bad you should donate mustard oil.',
  'Ve-12':
    'According to Lal Kitab birth chart, Venus is in house 12 in your chart. Venus is also said to be the abode of Lakshmi in this house. The native gets happiness of wife till 37 years after marriage. You are someone who gives good advice and your advice is useful to people. Your old age will be spent well. You exaggerate your small illnesses a lot. If you take care of your wife it will be very auspicious for you. If you are religious it is auspicious for you. Your wife may be talkative and suspicious by nature. Keeping brother-in-law (sala) with you is inauspicious. Serving a white cow is auspicious for you.',
};

/** Birth chart Lal Kitaab — planet-in-house remedies in English (translated from Hindi). */
export const BIRTH_CHART_PLANET_IN_HOUSE_REMEDIES: Record<string, string[]> = {
  'Ke-1': ['Offer coconut at temple', 'Keep a black or white dog', 'Do Mercury remedy', 'Feed jaggery to monkey', 'Do Moon remedy', 'Keep a red handkerchief in your pocket', 'Donate black and white blanket at temple'],
  'Ke-2': ['Apply saffron tilak on forehead', 'Keep conduct right', 'Serve young girls', 'Wear gold on neck', 'Getting nose pierced at appropriate time will give you excellent results'],
  'Ke-3': ['Offer rice, jaggery and milk in flowing water', 'Wearing gold in ears is auspicious', 'Do not keep sister-in-law or brother-in-law at home with you', 'Do not use green colour', 'Offer Sun and Moon items in flowing water', 'Apply saffron tilak'],
  'Ke-4': ['Offer Jupiter items in flowing water', 'Keeping a dog will be auspicious for you', 'Wear silver for peace of mind', 'Offer yellow lemons in flowing water', 'Donate Sun items and take blessings', 'Donate yellow items and clothes'],
  'Ke-5': ['Donate Moon and Mars items', 'Perform ancestors\' shradh properly', 'Apply saffron tilak', 'Do Jupiter remedy', 'Donate yellow items and clothes'],
  'Ke-6': ['Do not drink plain milk; drink milk with saffron', 'Donate black and white blanket at temple', 'Do Jupiter remedy', 'Wear gold ring on left hand', 'Keeping a dog is auspicious for you', 'Donate bananas at temple for 43 days continuously'],
  'Ke-7': ['Do not make false promises to anyone', 'Do not be proud', 'Offer 4 lemons in flowing water for 4 days', 'Never speak bitter words', 'Donate Saturn items at temple'],
  'Ke-8': ['Keep your conduct right then your wife\'s health will remain fine', 'Worship Lord Ganesha', 'Feed roti to dog', 'Donate blankets at temples', 'Getting ears pierced and wearing gold will give you auspicious results', 'Apply saffron tilak'],
  'Ke-9': ['Wear gold in ears', 'Donate to Brahmin', 'Keep a gold brick at your home', 'Keep a dog at your home', 'Do Jupiter remedy'],
  'Ke-10': ['Stay away from other women', 'Do Jupiter remedy', 'Do Moon remedy', 'Do not speak ill of your brothers', 'Keep a pot-shaped vessel filled with honey at home', 'Keeping a dog after 48 years of age is auspicious for you', 'Bury honey under the foundation of the house'],
  'Ke-11': ['Keep radish near your wife\'s pillow at night and offer it at a religious place in the morning for good effect on your progeny', 'Drink milk with saffron', 'Keeping a black dog is auspicious for you', 'Donate Jupiter items', 'Wear yellow clothes on Jupiter day'],
  'Ke-12': ['Worship Lord Ganesha', 'Keeping a dog is auspicious for you', 'If your progeny is troubled do Rahu remedy', 'Keep your conduct right', 'You should care for your progeny', 'If your pet dog dies, get another dog within 43 days'],
  'Ma-1': ['Do not work with your brother-in-law (sala)', 'Serving peepal is auspicious for you', 'Donate chickpea flour etc. at temple', 'Do not speak ill of anyone', 'Do not take anything free from anyone', 'If you take things free from anyone your blood becomes like water', 'Do not keep ivory or elephant idol at home'],
  'Ma-2': ['Feed jaggery to children in the afternoon', 'Helping others will make your fortune rise', 'If you insult your brother you may face loss', 'Donate rice, silver, milk and water at temple or gurudwara', 'Arrange water at in-laws\' place', 'Use red handkerchief'],
  'Ma-3': ['Wear silver ring without joint on index finger', 'Do not show arrogance in any work; it is not auspicious for you', 'Keeping ivory at home will be auspicious', 'Honey and sugar business will be inauspicious for you', 'If your Mars is bad you may have stillborn progeny'],
  'Ma-4': ['Clean teeth with water every morning', 'Offer sweet milk at banyan root and apply tilak with wet clay', 'Serving Brahmin, mother and monkey is auspicious for you', 'Fill earthen pot with honey and bury it at cremation ground', 'Sleeping on deer skin is auspicious for you', 'If your house door is south-facing fix 400 grams of bananas on the frame', 'Stay away from dark, one-eyed, lame and childless person', 'Keep ivory at home', 'Feed sweets to ants'],
  'Ma-5': ['Keep your conduct right', 'Serve elders', 'Plant neem trees will be auspicious for you', 'Avoid relations with other women', 'Keep water near head at night and pour in a plant in morning', 'Donate milk'],
  'Ma-6': ['Help maternal uncle, maternal aunt, mother, sister, daughter and aunt etc. from time to time', 'Worship Lord Ganesha', 'At progeny\'s birth distribute salty along with sweet', 'Celebrating your progeny\'s birthday will harm you', 'Do Saturn remedy', 'Feed girls for 6 days', 'Ask your progeny to wear gold items'],
  'Ma-7': ['Keep helping your brother and nephew', 'Whenever sister comes home feed her sweet and then send her back', 'Keeping silver at home will benefit you', 'Do not plant broad-leaved tree', 'Do not keep goat and cow at home', 'Give red clothes to your aunt and sister after marriage', 'Keep doing Saturn and Venus remedies'],
  'Ma-8': ['Wear silver chain on neck', 'For 43 days get sweet roti baked in tandoor and give to dogs; ensure no iron touches the roti', 'Donate rice and chickpea dal at temple', 'Do not keep tandoor at home', 'Do not keep ivory at home', 'Make a room at the end of the house', 'Eating in kitchen is auspicious for you', 'Do not insult any widow and keep taking widow\'s blessings', 'Sprinkle water on hot griddle and make roti', 'Fill earthen pot with honey and bury at cremation ground'],
  'Ma-9': ['Stay with elder brother and work with him', 'Serve sister-in-law (bhabhi)', 'Bury Venus items in ground; then you will not be punished by any woman', 'Donate milk, curd and silver at temple', 'Keeping red handkerchief is auspicious for you'],
  'Ma-10': ['Do not sell gold jewellery at home', 'Take care while boiling milk that it does not fall on ground', 'Do not sell ancestral land/property', 'If possible serve deer', 'Serving dark, one-eyed and childless person will be auspicious for you', 'If Mars is bad wear 3-star ring'],
  'Ma-11': ['Keeping honey at home will be auspicious for you', 'Fill 2 glass jars with jaggery and bury in deserted place', 'Do not sell ancestral property', 'Keep a dog at home or install 3 clay dog figures at home'],
  'Ma-12': ['Feeding sweet roti to dogs is auspicious for you', 'Offering water to Sun with sugar is auspicious for you', 'Using red cap or handkerchief is auspicious for you', 'Donating candy at temple is auspicious for you', 'Keeping saunf near your head at night while sleeping is auspicious for you', 'Your elder brother should not wear red clothes'],
  'Me-1': ['Working in one place is auspicious for you', 'Do not consume or use green items', 'Consuming alcohol and egg will be inauspicious for you', 'Consuming fish is very inauspicious for you', 'Do not keep sister-in-law (sali) with you', 'Getting nose pierced is auspicious for you', 'Keep water near head at night and pour in peepal in morning'],
  'Me-4': ['Feed jaggery and chickpeas to monkey', 'Wearing silver chain for peace of mind is auspicious for you', 'Stay away from green items and do not plant trees at home', 'Donating rice and milk will give you good results', 'Donate gold or brass items to priest'],
  'Me-5': ['Wearing copper coin on neck will give auspicious results', 'You should not speak ill of anyone because words from your mouth come true', 'Keeping cow will be lucky for you, your progeny and your wife', 'Using kikar for tooth-cleaning is auspicious for you', 'Wearing Moon and Sun items will benefit you', 'Gomukhi house will be auspicious for you'],
  'Me-6': ['Your sister and daughter\'s in-laws should not be in north direction', 'Before starting any work take blessings of girls', 'Wearing silver ring on wife\'s left hand will be auspicious for you', 'Bury bottle of Ganga water in farmland', 'When building new house do not keep door towards north'],
  'Me-7': ['Never gamble', 'You should wear emerald or diamond', 'Do not do partnership business with anyone', 'Respect sisters as mother', 'Always keep distance from spoilt sister-in-law (sali)'],
  'Me-9': ['Do not take any amulet from any fakir or sadhu', 'Donate mushroom in earthen pot at temple', 'Never keep parrot or goat', 'Do not use green items', 'Wearing silver ring in nose is auspicious for you', 'Keep red round pills with you', 'Do not sign any paper without reading'],
  'Me-10': ['Do Saturn remedy', 'Consuming alcohol, meat and egg will be inauspicious for you', 'You should not plant money plant or tulsi at home', 'Give some pieces of your roti to crow', 'Donating milk and rice at temple is auspicious for you'],
  'Me-11': ['Keep copper vessel filled with Ganga water at home', 'Keep distance from green items', 'Do not plant broad-leaved tree at home', 'Wearing copper coin will be auspicious for you', 'Do not keep empty vessel covered; put something in it'],
  'Me-12': ['Apply saffron tilak daily', 'Control your speech', 'Do not take ring free from anyone', 'Worshipping Lord Ganesha is auspicious for you', 'Wearing yellow thread on neck will be auspicious for you', 'Keeping black or white dog is auspicious for you; ensure it is not brown', 'Floating empty pot in water is auspicious for you', 'Going to temple daily is auspicious for you'],
  'Mo-1': ['Offering water at the root of big trees is auspicious for you', 'You should fix copper nails in the four legs of your bed', 'Drink milk and water in a silver vessel', 'Do not use glass vessel for milk and water at all', 'Donate milk and do not do milk business at all', 'Take silver or rice from mother and keep at home', 'Do not build house before 24 years', 'In the 24th year keep a cow at home or take a maid\'s services'],
  'Mo-2': ['Donate green clothes to girls for 43 days', 'Serve the elderly woman of the family', 'Bury silver brick and silver items in the foundation of the house', 'Keep some part of the house with raw earthen floor', 'Take rice and silver from your mother, tie in white cloth and keep safely at home'],
  'Mo-3': ['Donating Sun-related items is beneficial', 'Do not take money from your daughter and in-laws', 'Do kanyadaan without fail', 'Worship the form of Mother Durga', 'Serving and fulfilling the needs of women at home will be auspicious for you'],
  'Mo-4': ['Bowing at a religious place is auspicious for you', 'Milk business is harmful for you', 'Burning milk is harmful for you i.e. making mawa is harmful for you', 'Welcome guests at home with milk', 'Take blessings of elderly women at home', 'Do not fear spending; the more you spend the more money will come to you', 'Stay away from women of bad character'],
  'Mo-5': ['Self-interest and greed are inauspicious for you', 'Visiting hilly places is auspicious for you', 'On Monday tie rice and mishri in white cloth and float in flowing water', 'Consume jaggery before leaving home', 'Do not speak inauspiciously about anyone', 'Do not abuse anyone', 'Doing auspicious work for public welfare will increase your wealth'],
  'Mo-6': ['You should feed milk to your father with your own hands', 'Donating items of Moon\'s friend planets—Sun, Mars and Jupiter—at the temple will be auspicious for you', 'You can donate milk at the temple', 'Arranging water at hospital and cremation ground will be auspicious for you; donating water elsewhere will be inauspicious', 'You can use curd or paneer', 'You should not drink milk at night', 'Serving rabbit will be auspicious for you'],
  'Mo-7': ['Ensure your marriage does not happen at 24 years', 'At marriage take silver items from in-laws', 'Keep water at home equal to your weight', 'Do not do milk and water business', 'Do not make mawa from milk', 'Do not burn milk'],
  'Mo-8': ['Perform shraddh of elders', 'Keep away from lies and deceit', 'Offer one and a quarter kg chana dal on Shivling at temple', 'Arrange water at the cremation ground', 'Do not build house where there is already a well', 'Fill milk in a bottle and bury in the forest', 'Donate milk at the time of pitru donation', 'Stay away from other women', 'Piercing nose will be auspicious for you', 'Do not consume meat and alcohol', 'Do not gamble'],
  'Mo-9': ['Keep your character right', 'Going to temple daily is auspicious for you', 'Installing items of Moon\'s friend planets at home will be auspicious'],
  'Mo-10': ['Jupiter remedy will be auspicious for you', 'If you are a doctor do not give medicines free', 'Do not keep milch animals at home', 'Do not drink milk at night', 'Do not keep too much relation with in-laws', 'Do not help widowed women', 'Keep rainwater at home for 10 years', 'Go to any temple daily'],
  'Mo-11': ['Your mother should go elsewhere at the time of your child\'s birth or should not see your child\'s face for 43 days', 'Never install a hand-pump', 'Donate milk at Bhairav temple', 'Feed white peda to 11 children or 11 persons', 'Go to temple barefoot for 43 days', 'Do not do worship at night'],
  'Mo-12': ['Keep rainwater at home', 'Start any work only after drinking water', 'Wear gold in ear', 'Wear ring of gold, silver and copper', 'Do Jupiter remedy', 'Keep your word; do not repeat in mind'],
  'Ra-1': ['You should not wear black and blue clothes', 'Bathing with milk is auspicious for you', 'You should wear silver on neck', 'Donate Sun-related items', 'Float coconut in flowing water', 'Keep barley near head while sleeping at night and offer it in water in morning'],
  'Ra-2': ['Never build temple at home', 'Apply turmeric or saffron tilak', 'Wearing gold will be auspicious for you', 'Maintain good relations with mother at home', 'Keep some silver item with you for auspicious results', 'Do not take electrical items from in-laws at marriage'],
  'Ra-3': ['Do Moon remedy', 'Keep ivory with you for auspicious results', 'Keep rice in silver box for auspicious results', 'Keeping silver toy will give inauspicious results'],
  'Ra-4': ['Do not build kitchen under stairs of house', 'Wearing silver is auspicious for you', 'Take Ganga bath', 'Offer 400 gm coriander in flowing water', 'Offering 500 gm almonds in flowing water is auspicious for you', 'Complete whatever work you do at home; do not leave incomplete'],
  'Ra-5': ['If you have progeny-related trouble donate almonds at temple for 43 days', 'Stay away from other women', 'Do not consume alcohol, meat and egg at all', 'Person with Rahu in 5 should not wear blue sapphire', 'If your Rahu is not good you should remarry your wife', 'If your wife dies do not marry again'],
  'Ra-6': ['Keeping black dog is auspicious for you', 'Do not install black glass window at home', 'Help your siblings', 'Keep any black item in your pocket', 'Worship Mother Saraswati'],
  'Ra-7': ['Float 4 coconuts in flowing water', 'Take silver brick from in-laws at marriage', 'Never keep a dog', 'If your marriage happened at 21 years donate a vessel filled with Ganga water at temple', 'Keeping silver brick at home is auspicious for you'],
  'Ra-8': ['Donate almonds at temple', 'Never lie', 'Float coconut in flowing water', 'Put 8 copper coins in furnace', 'Keep silver items with you'],
  'Ra-9': ['Wearing gold is auspicious for you', 'Do Jupiter remedy', 'Do not wear black and blue clothes', 'You should keep a tuft in your hair', 'Apply saffron tilak daily', 'Respect your father and take his blessings', 'Going to temple daily will benefit you', 'Keep good relations with in-laws', 'Do not take electrical items free from in-laws or any friend'],
  'Ra-10': ['Do not drink milk at night', 'Keeping tuft on head is auspicious for you', 'Do Mars remedy', 'Native should keep head covered', 'Wearing cap or turban is auspicious for you', 'Feed 10 blind people with your own hands', 'Float 4 kg desi sugar in water'],
  'Ra-11': ['Donate Jupiter items', 'Do not consume onion at all on Thursday', 'On 8th birthday float 4 dry coconuts in flowing water', 'After father\'s death eat yellow food and wear yellow clothes more', 'Wearing gold is auspicious for you', 'Apply saffron tilak', 'Donate coins to sweeper; remember not to give paper notes'],
  'Ra-12': ['Keep saunf, sugar or moong dal under pillow while sleeping at night; will be auspicious for you', 'Sit where food is cooked and eat; auspicious for you', 'Do not overthink', 'Make a dark room in your house', 'Give some part of your income to sister or daughter', 'Float 12 kg raw coal in water'],
  'Sa-1': ['Keep or serve monkeys', 'Do not lie', 'Donating iron tongs is auspicious for you', 'Donate mustard oil', 'Offer sweet milk at banyan or banana root and apply wet clay tilak'],
  'Sa-2': ['Feeding milk to snake is auspicious for you', 'Offer water on Shivling at temple', 'Keeping brown buffalo will be auspicious for you', 'If health is bad use Rahu-related items', 'Go to temple barefoot for 43 days and bow'],
  'Sa-3': ['Keeping dog at home is auspicious for you', 'When building house make dark room', 'Fix nails on doorstep of house', 'Doing Ketu remedy will get you wealth', 'Consuming meat and alcohol is inauspicious for you'],
  'Sa-4': ['Feed roti to crow', 'Feed milk to snake', 'Keep buffalo or feed roti for benefit', 'Serve labourers', 'Stay away from other women', 'Never drink milk at night', 'Never wear black clothes', 'Stay away from green', 'Never kill snake'],
  'Sa-5': ['Do not distribute sweet when progeny is born; if you do distribute salty with it', 'Doing Mercury remedy will benefit you', 'You should not build your house till 48 years', 'If your progeny builds house from own earnings it is auspicious for you', 'Keeping dog is auspicious for you', 'Go to temple and offer 10 almonds and bring half back and keep in tin box closed'],
  'Sa-6': ['Keeping black and brown dog is auspicious for you', 'Donating shoes to a poor person will benefit you', 'When ill float 6 coconuts for 6 days continuously', 'Float almonds in flowing water', 'Serving snake is auspicious for you', 'Do Mercury remedy'],
  'Sa-7': ['Do not partner with anyone', 'Keep copper vessel filled with honey at home', 'Serve black cow', 'Stay away from other women otherwise progeny will suffer', 'Do not consume alcohol'],
  'Sa-8': ['Wear silver', 'Do not eat meat', 'Float 8 almonds in flowing water', 'Adding milk to water while bathing will be auspicious for you', 'Float 8 kg urad dal in flowing water', 'Soak dates in water', 'Never consume intoxication'],
  'Sa-9': ['Doing Jupiter remedy will benefit you', 'If troubled after parents\' death install stone somewhere at home', 'Make dark room at back of house', 'Keep house roof always clean', 'Float rice and almonds in flowing water'],
  'Sa-10': ['Worship Lord Ganesha', 'Keep head covered with white cap or clothes', 'Float chickpea dal in water for 40 days', 'Respect others', 'Do not consume alcohol, meat and egg', 'Drinking milk at night is harmful for you'],
  'Sa-11': ['Stay away from other women', 'Do not build house gate in south direction', 'Do Jupiter remedy', 'Keep silver brick at your home', 'Donate oil after seeing your shadow in oil', 'Do not cheat anyone', 'Doing Jupiter remedy will be auspicious for you'],
  'Sa-12': ['Do not lie', 'Stay away from other women', 'Do not build window or door at back of house', 'You should keep your conduct right', 'Person should make dark room in house', 'Consuming alcohol and meat is inauspicious for you', 'Wrap 12 almonds in black cloth and keep in iron box and never open'],
  'Su-1': ['If house 5 is empty in your chart you should wear items of Sun\'s friend planets', 'You should marry before 24 years', 'You should install handpump or natural water source in your ancestral home', 'You should build dark room on left side in your house'],
  'Su-2': ['You should never take donation; do not take any item without paying', 'Do not take rice, silver, milk in donation', 'Do not take wheat, bajra or any item in donation'],
  'Su-3': ['Keep your conduct right', 'Help poor children', 'Take blessings of women of house', 'Take full care of women of house', 'Stay away from sin and bad deeds'],
  'Su-4': ['If you have left ancestral house still you should feed roti to blind near that house', 'Do not consume alcohol and meat', 'Wear copper coin in khaki thread on neck', 'Do gold, silver and cloth work', 'Do not do iron and wood work'],
  'Su-5': ['Serving red-mouthed small monkey will be beneficial', 'Serving three types of dogs i.e. brother-in-law, son-in-law and grandson etc. is auspicious', 'You should build kitchen in east direction only in your house', 'Serve birds and hens'],
  'Su-6': ['You should feed jaggery to monkeys', 'After dinner at night extinguish stove fire with milk', 'Feed powder of seven dals to ants', 'Install Ganga water or silver at home', 'Keeping dog will be auspicious for you'],
  'Su-7': ['Consume jaggery and water when leaving home', 'Put ¼ or some part of your roti in fire', 'Serve black cow', 'Give your wife gold clip in hair i.e. make wife wear gold on head'],
  'Su-8': ['Do not do Saturn-related work', 'Worship Lord Vishnu', 'Do not live in south-facing house', 'Donate 800 gm wheat and 800 gm jaggery at temple for 8 days continuously from Sunday; note chaturthi, navami and chaudas—do not start this on these tithis', 'Put copper coins on burning pyre at cremation ground', 'Start any new work only after eating jaggery and drinking water or consume a little jaggery and water when leaving home every morning'],
  'Su-9': ['Never take rice, silver or milk items in donation', 'Never sell old brass vessels', 'Control your anger and treat everyone equally'],
  'Su-10': ['Always wear white cap or turban', 'Serve brown buffalo', 'Apply saffron or yellow tilak', 'Do not wear blue clothes', 'Float copper coin in flowing water for 43 days', 'Always keep Ganga water at home', 'Install handpump inside house'],
  'Su-11': ['Keep radish, carrot and turnip near your head for 43 days and donate at temple in morning', 'Do not use alcohol, meat and egg even by mistake', 'Buy goat from butcher and leave in forest or buy 5 milk-giving goats equal to your weight and donate'],
  'Su-12': ['Feed jaggery to monkeys', 'Do not give false testimony', 'Do religious work from time to time', 'Sunlight must come into your house', 'Do not betray trust', 'Do not keep excessive relations with in-laws', 'Giving water at big trees\' root is auspicious for you', 'You should fix copper nails in all four legs of bed', 'Drink milk and water in silver vessel', 'Do not use glass vessel for milk and water', 'Donate milk and do not do milk business', 'Take silver or rice from mother and keep at home', 'Do not build house before 24 years'],
  'Ve-1': ['Do not consume jaggery', 'Serve black cow', 'Stay away from maid or other woman at home', 'Keep your conduct right', 'You should donate 200 gm yellow ghee of cow at temple'],
  'Ve-2': ['Taking wife\'s advice for work is auspicious for you', 'Gold business can cause you loss', 'Offering Mars items, saunf, honey and sugar etc. in flowing water is auspicious for you', 'Do not light ghee lamp at home', 'Feed cow 2 kg potato coloured yellow with turmeric for auspicious results', 'Have faith in God', 'Bathe with curd', 'Do not eat jaggery'],
  'Ve-3': ['Using Mars items is auspicious for you', 'Respecting woman and not insulting her will give you auspicious results', 'Never play music at home', 'Stay away from other women; do not have any relation'],
  'Ve-4': ['Moon remedy or putting Jupiter items in well is auspicious for you', 'You should not dig well at home', 'Do Jupiter remedy', 'Do not consume intoxication', 'You should hide your bad habits and proclaim virtues', 'Remarrying your wife will be auspicious for you'],
  'Ve-5': ['Serving cow and feeding fodder is auspicious for you', 'Keeping silver vessel filled with water at home is auspicious for you', 'Marry with parents\' wish', 'Keep your character right', 'Avoid love affairs', 'You should not have relations with anyone other than your wife'],
  'Ve-6': ['Respect women', 'Donate milk and rice at religious place', 'Keep conduct right and keep distance from other women', 'Put gold clip in wife\'s hair', 'Do not let wife walk barefoot on ground', 'Never insult women', 'Keep solid silver pill with you'],
  'Ve-7': ['You should take parents\' blessings daily', 'Serving red cow is auspicious for you', 'Donating brass vessel at temple on Friday is auspicious for you', 'Putting blue flower in dirty drain for 43 days is auspicious for you', 'Doing business with brothers is auspicious for you'],
  'Ve-8': ['Make flour ladoo with jaggery for black cow and give on 8 Fridays for auspicious results', 'Bowing at temple will weaken your enemy', 'Never take donation', 'Marrying after 25 years is auspicious for you', 'Serving black cow is auspicious for you', 'Donate jimikand or carrot (800 gm or 8 kg) at temple', 'Feeding green fodder to cow is auspicious for you; more auspicious if you feed fodder equal to your weight'],
  'Ve-9': ['Do not consume plain white curd; eat mixed', 'Son\'s marriage only after 25 years of age is auspicious for you', 'Serving white cow will give inauspicious results', 'Serving black cow is auspicious for you', 'Make wife wear silver bangles coloured red for your benefit', 'If relations with wife are not good do cow donation'],
  'Ve-10': ['Consuming alcohol is inauspicious for you', 'Doing Saturn remedy is auspicious for you', 'Stay away from other women', 'Do not kill fish', 'Keep west wall of your house raw', 'Donate almonds at temple'],
  'Ve-11': ['Donating Mars items at temple is auspicious for you', 'Donating oil on Saturday is auspicious for you', 'Donate curd at temple', 'Doing Mercury remedy is auspicious for you', 'Do not give locker key to woman i.e. do not make her owner', 'Donating black cow or red cow at marriage is auspicious for you'],
  'Ve-12': ['Light desi ghee lamp at your home', 'Giving respect and love to your wife is auspicious for you', 'Serving white cow will give auspicious results', 'Do not keep any relation with Rahu items', 'Donating jowar equal to woman\'s weight at temple is auspicious for you'],
};
